### ISSUE TITLE
"GCJ-09" instead of 02 in published PDF

### ISSUE THREAD

**Issue by dandv** [caijun/geoChina#1]
Hi Jun,

I've found [this PDF](http://dssm.unipa.it/CRAN/web/packages/geoChina/geoChina.pdf) which apparently describes your work.

1) The lead paragraph there has an error: it mentions "GCJ-09" instead of "GCJ-02".
2) That PDF is hosted by the University of Palermo in Italy. Is it generated from your code, or is it a paper you've published elsewhere? Do you have a link to your original paper?

**Comment by caijun** [comment]
The PDF you found is the manual generated from my package geoChina version 1.0, which I firstly released on CRAN. Later I deleted geoChina from CRAN and maintain it on my github. 

Thanks for your correction. The "GCJ-02" in the description of geoChina version 1.0 is a typo. I have already corrected it in later versions. You can use the latest version of geoChina from my github. There is no paper for the package yet. If you have any questions about the package, you can open issues or email to me.

**Comment by dandv** [comment]
That clears things up. Thank you, and I'll close this issue.
