### ISSUE TITLE
fail to install

### ISSUE THREAD

**Issue by yafeiguo** [caijun/geoChina#6]
* installing *source* package 'geoChina' ...
** R
Warning: unable to re-encode 'geocode.R' lines 170, 172, 174, 176, 180
** inst
Warning in file.create(to[okay]) :
  cannot create file '\files.brown.edu/Home/yguo26/Documents/R/win-library/3.3/geoChina/CITATION', reason 'No such file or directory'
** tests
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'Rcpp'
ERROR: lazy loading failed for package 'geoChina'
* removing '\\files.brown.edu/Home/yguo26/Documents/R/win-library/3.3/geoChina'
Error: Command failed (1)

**Comment by yafeiguo** [comment]
> devtools::install_github("caijun/geoChina")
Downloading GitHub repo caijun/geoChina@master
from URL https://api.github.com/repos/caijun/geoChina/zipball/master
Installing geoChina
Installing 1 package: plyr
Installing package into ‘\\files.brown.edu/Home/yguo26/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/plyr_1.8.4.zip'
Content type 'application/zip' length 1184211 bytes (1.1 MB)
downloaded 1.1 MB

package ‘plyr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\yguo26\AppData\Local\Temp\RtmpANOKfa\downloaded_packages
Installing 1 package: RJSONIO
Installing package into ‘\\files.brown.edu/Home/yguo26/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/RJSONIO_1.3-0.zip'
Content type 'application/zip' length 1491357 bytes (1.4 MB)
downloaded 1.4 MB

package ‘RJSONIO’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\yguo26\AppData\Local\Temp\RtmpANOKfa\downloaded_packages
"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/yguo26/AppData/Local/Temp/RtmpANOKfa/devtools1b9c154e4098/caijun-geoChina-6151e45"  \
  --library="\\files.brown.edu/Home/yguo26/Documents/R/win-library/3.3"  \
  --install-tests 

* installing *source* package 'geoChina' ...
** R
Warning: unable to re-encode 'geocode.R' lines 170, 172, 174, 176, 180
** inst
Warning in file.create(to[okay]) :
  cannot create file '\files.brown.edu/Home/yguo26/Documents/R/win-library/3.3/geoChina/CITATION', reason 'No such file or directory'
** tests
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'Rcpp'
ERROR: lazy loading failed for package 'geoChina'
* removing '\\files.brown.edu/Home/yguo26/Documents/R/win-library/3.3/geoChina'
Error: Command failed (1)

**Comment by caijun** [comment]
在`geocode.R`170, 172, 174, 176, 180行存在中文注释。整个代码文件都是utf8编码的，有人在windows上安装成功过。因此可能是你的电脑编码问题。

**Comment by yafeiguo** [comment]
谢谢您的快速回复。
我再确认一下电脑的编码识别。

非常感谢！

亚菲

**Comment by caijun** [comment]
你先试试，如果不行的话，我会考虑将中文注释换成英文的，更新一下geoChina。

**Comment by yafeiguo** [comment]
好的。这个问题我是在学校图书馆计算机安装使用时遇到的。文字编码出问题的可能比较大。

明天我试完回复你。

**Comment by yafeiguo** [comment]
Sorry, it still not works.
"Warning: unable to re-encode 'geocode.R' lines 170, 172, 174, 176, 180"
I use this code in public computer of library, that is unavailable to install anything.

**Comment by caijun** [comment]
I have replaced Chinese comments in `geocode.R` with English comments. You can try the newest version of geoChina to see whether it fixes your problem.
