### ISSUE TITLE
Algorithm behind coordinates conversion?

### ISSUE THREAD

**Issue by versey-sherry** [caijun/geoChina#7]
Thanks for this great package! I don't see how you achieve the coordinates conversion between different types of coordinates, especially from BD09 to WGS84. I know that you convert BD09 to GCJ02 first but how did you convert BD09 to GCJ02?

Thanks for answering in advance.

**Comment by caijun** [comment]
After converting BD09 into GCJ02, calling `gcj2wgs()` can convert the resulting GCJ02 coordinates into WGS84 coordinates.

**Comment by versey-sherry** [comment]
How exactly does the conversion from BD09 to GCJ02 work? As far as I know, Baidu API only provides coordinates conversion to BD09 but not the other direction

**Comment by caijun** [comment]
Please read the manual of geoChina package https://github.com/caijun/geoChina/blob/master/R/cst.R#L199
http://blog.csdn.net/coolypf/article/details/8569813
The conversion algorithm is from the web, and I can't guarantee its correctness.
