### ISSUE TITLE
wgs842gcj02 is too slow than recharts2::geoCoord in batch mode

### ISSUE THREAD

**Issue by harryprince** [caijun/geoChina#9]
I am using dplyr to batch convert wgs84 to gcj02 coordinate. Indeed, geoChina is too slow than 
recharts2::geoCoord.

* https://github.com/madlogos/recharts2/blob/master/R/geoCoord.R

**Comment by harryprince** [comment]
Currently, best practice is 

```{r}
new_df = bind_cols(
    df %>% recharts2::geoCoord(.$lat,.$lng),
    df %>% select(-lat,-lng)
)
```

**Comment by caijun** [comment]
Thanks for your information. I looked at the code in https://github.com/madlogos/recharts2/blob/master/R/geoCoord.R. I believe the author has referred to my code. Some code and documentation are from mine. Perhaps he implemented the conversion functions more efficiently. 

In practice, I actually try to slow down the speed of geocoding as it calls the Google Map Geocoding API. If we calls the Google Map Geocoding too frequently, the success of geocoding will be low. With respect to this, if you have any suggestion, please let me know.

**Comment by harryprince** [comment]
In industry, I need to parallel processing the coordinate conversion. Calling Google Map API might be fail for my scenario.

**Comment by mingR** [comment]
> Currently, the best practice is
> 
> ```
> new_df = bind_cols(
>     df %>% recharts2::geoCoord(.$lat,.$lng),
>     df %>% select(-lat,-lng)
> )
> ```
Hi Harry?

I wonder what's your current best practice, as recharts2 has stopped development?
